//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace PEPmodnaKompanija_PCL.Model
{

    
    public class Narudzbe
    {
        public Narudzbe()
        {
        
            this.NarudzbaStavke = new HashSet<NarudzbaStavke>();
        }
    
        public int NarudzbaID { get; set; }
        public string BrojNarudzbe { get; set; }
        public int KupacID { get; set; }
        public System.DateTime Datum { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> Otkazano { get; set; }
        public int AdresaDostaveID { get; set; }
        public int NacinDostaveID { get; set; }
        public int NacinPlacanjaID { get; set; }

        public virtual AdresaDostave AdresaDostave { get; set; }
        public virtual NacinDostave NacinDostave { get; set; }
        public virtual NacinPlacanja NacinPlacanja { get; set; }
        public double Iznos { get; set; }
        public virtual Kupci Kupci { get; set; }
        public virtual ICollection<NarudzbaStavke> NarudzbaStavke { get; set; }
    }
}
