//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPmodnaKompanija_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdresaDostave
    {
        public AdresaDostave()
        {
            this.Narudzbe = new HashSet<Narudzbe>();
        }
    
        public int AdresaDostaveID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string PostanskiBroj { get; set; }
        public string Ulica { get; set; }
        public string Drzava { get; set; }
    
        public virtual ICollection<Narudzbe> Narudzbe { get; set; }
    }
}
