//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPmodnaKompanija_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavouiriteProizvod
    {
        public int FavouriteProizvodID { get; set; }
        public int FavouriteID { get; set; }
        public int ProizvodID { get; set; }
    
        public virtual Favourite Favourite { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
