//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPmodnaKompanija_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public Favourite()
        {
            this.FavouiriteProizvod = new HashSet<FavouiriteProizvod>();
        }
    
        public int FavouriteID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public int KupacID { get; set; }
    
        public virtual ICollection<FavouiriteProizvod> FavouiriteProizvod { get; set; }
        public virtual Kupci Kupci { get; set; }
    }
}
