//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPmodnaKompanija_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        public Korisnici()
        {
            this.Izlazi = new HashSet<Izlazi>();
            this.LookBook = new HashSet<LookBook>();
            this.Proizvodi = new HashSet<Proizvodi>();
            this.Revije = new HashSet<Revije>();
            this.Katalog = new HashSet<Katalog>();
            this.SkladisteProizvodi = new HashSet<SkladisteProizvodi>();
            this.OcjeneDizajnera = new HashSet<OcjeneDizajnera>();
        }
    
        public int KorisnikID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string KorisnickoIme { get; set; }
        public string LozinkaHash { get; set; }
        public string LozinkaSalt { get; set; }
        public bool Status { get; set; }
        public Nullable<int> UlogaID { get; set; }
    
        public virtual ICollection<Izlazi> Izlazi { get; set; }
        public virtual Uloge Uloge { get; set; }
        public virtual ICollection<LookBook> LookBook { get; set; }
        public virtual ICollection<Proizvodi> Proizvodi { get; set; }
        public virtual ICollection<Revije> Revije { get; set; }
        public virtual ICollection<Katalog> Katalog { get; set; }
        public virtual ICollection<SkladisteProizvodi> SkladisteProizvodi { get; set; }
        public virtual ICollection<OcjeneDizajnera> OcjeneDizajnera { get; set; }
    }
}
