//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPmodnaKompanija_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modeli
    {
        public Modeli()
        {
            this.ModelLookBook = new HashSet<ModelLookBook>();
            this.ModeliProizvodi = new HashSet<ModeliProizvodi>();
        }
    
        public int ModelID { get; set; }
        public byte[] Slika { get; set; }
        public byte[] SlikaThumb { get; set; }
        public string Opis { get; set; }
        public string Naziv { get; set; }
        public int RevijaID { get; set; }
    
        public virtual Revije Revije { get; set; }
        public virtual ICollection<ModelLookBook> ModelLookBook { get; set; }
        public virtual ICollection<ModeliProizvodi> ModeliProizvodi { get; set; }
    }
}
