//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPmodnaKompanija_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NacinDostave
    {
        public NacinDostave()
        {
            this.Narudzbe = new HashSet<Narudzbe>();
        }
    
        public int NacinDostaveID { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<Narudzbe> Narudzbe { get; set; }
    }
}
