//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPmodnaKompanija_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbe
    {
        public Narudzbe()
        {
            this.Izlazi = new HashSet<Izlazi>();
            this.NarudzbaStavke = new HashSet<NarudzbaStavke>();
        }
    
        public int NarudzbaID { get; set; }
        public string BrojNarudzbe { get; set; }
        public int KupacID { get; set; }
        public System.DateTime Datum { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> Otkazano { get; set; }
        public int AdresaDostaveID { get; set; }
        public int NacinDostaveID { get; set; }
        public int NacinPlacanjaID { get; set; }
    
        public virtual ICollection<Izlazi> Izlazi { get; set; }
        public virtual Kupci Kupci { get; set; }
        public virtual ICollection<NarudzbaStavke> NarudzbaStavke { get; set; }
        public virtual AdresaDostave AdresaDostave { get; set; }
        public virtual NacinDostave NacinDostave { get; set; }
        public virtual NacinPlacanja NacinPlacanja { get; set; }
    }
}
