//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPmodnaKompanija_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodi
    {
        public Proizvodi()
        {
            this.NarudzbaStavke = new HashSet<NarudzbaStavke>();
            this.Ocjene = new HashSet<Ocjene>();
            this.KatalogProizvod = new HashSet<KatalogProizvod>();
            this.FavouiriteProizvod = new HashSet<FavouiriteProizvod>();
            this.SkladisteProizvodi = new HashSet<SkladisteProizvodi>();
            this.ModeliProizvodi = new HashSet<ModeliProizvodi>();
        }
    
        public int ProizvodID { get; set; }
        public string Naziv { get; set; }
        public string Sifra { get; set; }
        public decimal Cijena { get; set; }
        public int VrstaID { get; set; }
        public byte[] Slika { get; set; }
        public byte[] SlikaThumb { get; set; }
        public bool Status { get; set; }
        public int SezonaID { get; set; }
        public int KorisnikID { get; set; }
        public int VelicinaID { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual ICollection<NarudzbaStavke> NarudzbaStavke { get; set; }
        public virtual ICollection<Ocjene> Ocjene { get; set; }
        public virtual Sezone Sezone { get; set; }
        public virtual VrsteProizvoda VrsteProizvoda { get; set; }
        public virtual ICollection<KatalogProizvod> KatalogProizvod { get; set; }
        public virtual ICollection<FavouiriteProizvod> FavouiriteProizvod { get; set; }
        public virtual ICollection<SkladisteProizvodi> SkladisteProizvodi { get; set; }
        public virtual Velicine Velicine { get; set; }
        public virtual ICollection<ModeliProizvodi> ModeliProizvodi { get; set; }
    }
}
