//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPmodnaKompanija_API.Models
{
    using System;
    
    public partial class RevijeByKorisnik
    {
        public string Naziv { get; set; }
        public System.DateTime Datum { get; set; }
        public string Napomena { get; set; }
        public int RevijaID { get; set; }
    }
}
