//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPmodnaKompanija_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skladista
    {
        public Skladista()
        {
            this.Izlazi = new HashSet<Izlazi>();
            this.SkladisteProizvodi = new HashSet<SkladisteProizvodi>();
        }
    
        public int SkladisteID { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<Izlazi> Izlazi { get; set; }
        public virtual ICollection<SkladisteProizvodi> SkladisteProizvodi { get; set; }
    }
}
