//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPmodnaKompanija_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Poruke {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Poruke() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PEPmodnaKompanija_UI.Poruke", typeof(Poruke).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum nije validan !  .
        /// </summary>
        internal static string datumRevije_err {
            get {
                return ResourceManager.GetString("datumRevije_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesena e-mail adresa je zauzeta. .
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste pogrešan format e-mail adrese !.
        /// </summary>
        internal static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite email !.
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite ime!.
        /// </summary>
        internal static string fname_req {
            get {
                return ResourceManager.GetString("fname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesena lozinka nije validna !.
        /// </summary>
        internal static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka treba da sadrži najmanje 6 karaktera..
        /// </summary>
        internal static string pass_err {
            get {
                return ResourceManager.GetString("pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite lozinku!.
        /// </summary>
        internal static string pass_req {
            get {
                return ResourceManager.GetString("pass_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete sliku dimenzija većih od.
        /// </summary>
        internal static string picture_war {
            get {
                return ResourceManager.GetString("picture_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o proizvodu..
        /// </summary>
        internal static string product_succ {
            get {
                return ResourceManager.GetString("product_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate označiti najmanje jednu ulogu!.
        /// </summary>
        internal static string radio_err {
            get {
                return ResourceManager.GetString("radio_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno popuniti ovo polje !.
        /// </summary>
        internal static string req {
            get {
                return ResourceManager.GetString("req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unijeti sliku !.
        /// </summary>
        internal static string slikaModela_req {
            get {
                return ResourceManager.GetString("slikaModela_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno odaberite najmanje jednu ulogu!.
        /// </summary>
        internal static string uloge_req {
            get {
                return ResourceManager.GetString("uloge_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o korisniku..
        /// </summary>
        internal static string user_succ {
            get {
                return ResourceManager.GetString("user_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime mora sadržavati više od 3 karaktera !.
        /// </summary>
        internal static string username_err {
            get {
                return ResourceManager.GetString("username_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite korisničko ime!.
        /// </summary>
        internal static string username_req {
            get {
                return ResourceManager.GetString("username_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
